### ISSUE TITLE
Update only specified gems

### ISSUE THREAD

**Issue by MaximeD** [MaximeD/gem_updater#1]
For some reason once my not want to update his whole gemset. Hence user should be able to list the gems for which he wishes an update.

Something like:
```
gem_update gem1 gem2
```

**Comment by scottrobertson** [comment]
:+1:

**Comment by MaximeD** [comment]
Hi all, you can now do this in the same way bundler does, example: `gem_update gem1 gem2`. Enjoy latest release!
