### ISSUE TITLE
GitHub changelog link anchors no longer found

### ISSUE THREAD

**Issue by mattmenefee** [MaximeD/gem_updater#162]
It appears that the format of GitHub's Changelog has changed slightly such that [this line](https://github.com/MaximeD/gem_updater/blob/v6.0.1/lib/gem_updater/source_page_parser.rb#L164) no longer works. I believe it's due to GitHub escaping the word "anchor" when specifying the CSS class on the `a` tag in more recent versions of its Markdown processor. In my local testing, I found that replacing:

```ruby
changelog_page.css(%(a.anchor))
```

with something like this using an XPATH selector:

```ruby
changelog_page.css(%(//a[contains(@class, "anchor")]))
```

seemed to have fixed the issue. You may need to update your VCR cassette in order to get a failing test.

**Comment by mattmenefee** [comment]
Fixed by #163

**Comment by mattmenefee** [comment]
@MaximeD thanks for the fix!

**Comment by MaximeD** [comment]
Thank you for reporting it, along with a way to fix it!
Version `6.0.2` has been released.
