### ISSUE TITLE
Gem update fails if source_code_uri in rubygems json response is included but has blank value

### ISSUE THREAD

**Issue by mattmenefee** [MaximeD/gem_updater#43]
If the json response from Rubygems includes the `source_code_uri` key but with a blank value, the method that determines the `uri_from_rubygems`, specifically this line:

```ruby
    response[ "source_code_uri" ] || response[ "homepage_uri" ]
```

will return a blank value, which when passed along to the `source_page_parser` will result in the following error:

```
/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:36:in `open': no implicit conversion of URI::Generic into String (TypeError)
from /.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:36:in `open'
from /.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gem_updater-0.4.2/lib/gem_updater/source_page_parser.rb:23:in `changelog'
from /.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gem_updater-0.4.2/lib/gem_updater.rb:53:in `block (2 levels) in fill_changelogs'
```

The gem that I have installed that I came across this error is [parser](https://github.com/whitequark/parser), which you can see has this issue from its [rubygems api response](https://rubygems.org/api/v1/gems/parser.json).

So I guess you should make sure that the `source_code_uri` key is both included and does not have a blank value before falling back to the `homepage_uri` (where you might want to perform the same check).

**Comment by MaximeD** [comment]
Thanks for reporting it and providing context for a gem that actually fails. As you said this is just a matter of checking that value is not blank, it will not be too hard to fix.
